#ifdef LUACONSOLE

const char* texter_luac = ""
"function gdText(text, r, g, b)\n"
"	local r, g, b = r, g, b\n"
"	function drawFontRect()\n"
"		local x, y = sim.adjustCoords(tpt.mousex, tpt.mousey)\n"
"		tpt.drawtext(x, y, text, r, g, b)\n"
"	end\n"
"	tpt.register_step(drawFontRect)\n"
"	function stopFontRect(x, y, _b, e)\n"
"		if e == 2 then\n"
"			local x, y = sim.adjustCoords(tpt.mousex, tpt.mousey)\n"
"			sim.plottext(x, y, text, r, g, b)\n"
"			tpt.unregister_step(drawFontRect)\n"
"			tpt.unregister_mouseclick(stopFontRect)\n"
"		end\n"
"		return false\n"
"	end\n"
"	tpt.register_mouseclick(stopFontRect)\n"
"end\n"
"local toPlot, toPlot2, r, g, b = 'Hello world!', '', 255, 255, 255\n"
"local winW, winH = 525, 170\n"
"gdtexter_key_test = function(a, _b, c, d)\n"
"	if a == 't' and c == 64 then\n"
"		local cmx, cmy = tpt.mousex, tpt.mousey\n"
"		local texterWindow = Window:new(305 - winW/2, 190 - winH/2, winW, winH)\n"
"		local currentY = 10\n"
"		local toPlotIn = Textbox:new(10, currentY, (select(1, texterWindow:size()))-20, 16, toPlot, \"[place text here]\")\n"
"		toPlotIn:onTextChanged(\n"
"			function(sender)\n"
"				toPlot = toPlotIn:text()\n"
"			end\n"
"		)\n"
"		currentY = currentY + 20\n"
"		--[[\n"
"		local toPlot2In = Textbox:new(10, currentY, (select(1, texterWindow:size()))-20, 16, toPlot2, \"[and here, if you need more space]\")\n"
"		toPlot2In:onTextChanged(\n"
"			function(sender)\n"
"				toPlot2 = toPlot2In:text();\n"
"			end\n"
"		)\n"
"		currentY = currentY + 20\n"
"		--]]\n"
"		local rl = Label:new(14, currentY, tpt.textwidth(\"Red\"), 16, \"Red\")\n"
"		currentY = currentY + 15\n"
"		local rIn = Slider:new(10, currentY, 255, 16, 255)\n"
"		rIn:onValueChanged(\n"
"			function(sender)\n"
"				r = rIn:value();\n"
"			end\n"
"		)\n"
"		rIn:value(255)\n"
"		currentY = currentY + 20\n"
"		local gl = Label:new(14, currentY, tpt.textwidth(\"Green\"), 16, \"Green\")\n"
"		currentY = currentY + 15\n"
"		local gIn = Slider:new(10, currentY, 255, 16, 255)\n"
"		gIn:onValueChanged(\n"
"			function(sender)\n"
"				g = gIn:value();\n"
"			end\n"
"		)\n"
"		gIn:value(255)\n"
"		currentY = currentY + 20\n"
"		local bl = Label:new(14, currentY, tpt.textwidth(\"Blue\"), 16, \"Blue\")\n"
"		currentY = currentY + 15\n"
"		local bIn = Slider:new(10, currentY, 255, 16, 255)\n"
"		bIn:onValueChanged(\n"
"			function(sender)\n"
"				b = bIn:value();\n"
"			end\n"
"		)\n"
"		bIn:value(255)\n"
"		local closeButton = Button:new(10, select(2, texterWindow:size())-26, 100, 16, \"Draw text\")\n"
"		closeButton:action(function()\n"
"			interface.closeWindow(texterWindow)\n"
"			gdText(string.gsub(toPlot, '\\\\n', '\\n'), r, g, b)\n"
"		end\n"
"		)\n"
"		texterWindow:onTryExit(function() interface.closeWindow(texterWindow) end) -- Allow the default exit events\n"
"		texterWindow:addComponent(toPlotIn)\n"
"		if toPlot2In then\n"
"			texterWindow:addComponent(toPlot2In)\n"
"		end\n"
"		texterWindow:addComponent(rIn)\n"
"		texterWindow:addComponent(gIn)\n"
"		texterWindow:addComponent(bIn)\n"
"		texterWindow:addComponent(rl)\n"
"		texterWindow:addComponent(gl)\n"
"		texterWindow:addComponent(bl)\n"
"		texterWindow:addComponent(closeButton)\n"
"		interface.showWindow(texterWindow)\n"
"	end\n"
"end\n"
"tpt.register_keypress(gdtexter_key_test)\n"
;
#endif